version: '3.8'
services:
  postgres:
    container_name: gastano_postgres
    image: postgres:17.5
    environment:
      POSTGRES_USER: gastano_admin
      POSTGRES_PASSWORD: gastano_senha123
      POSTGRES_DB: gastano_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gastano_admin -d gastano_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: gastano_app
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: gastano_admin
      DB_PASSWORD: gastano_senha123
      DB_NAME: gastano_db
      JWT_SECRET: MaxVerstappenFoiCampeaoEm2021PelaRedBull
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    